name: Automatically Deployment for Gatsby Blog

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
  
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.AUTO_DEPLOY_API_KEY }}
          deploy-branch: master
          gatsby-args: --verbose
